name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:
    types: [ship-it]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm install
      - run: npm run build

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "dist/main.js"

      - name: File contents
        run: echo "${ steps.read_file.outputs.contents }"
